server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: gestor_tareas
  flyway:
    enabled: true
    schemas: gestor_tareas
    baseline-on-migrate: true
    locations: classpath:db/migration
